# Generated by Django 5.1 on 2024-09-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='API_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
