# Generated by Django 5.1.1 on 2024-09-10 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_finder_app', '0002_alter_restaurant_api_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_restaurants', models.ManyToManyField(related_name='favorited_by', to='food_finder_app.restaurant')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_finder_app.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'restaurant')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
